
  const workerData = [
    {
      id: 1,
      phoneNumber: '1234567890',
      pin: '123456',
      role: 'worker',
      name: 'Muhammad Fadhil',
      job: 'Mobile App Development',
      photo: require('./photo/photoProfile.png'),
      productPhoto: require('./photo/project.png'),
      skills: [
        { id: 1, name: 'Skill 1', description: 'Low Fidelity Mockup', priceRange: '$50' },
        { id: 2, name: 'Skill 2', description: 'High Fid Prototype', priceRange: '$80' },
        { id: 3, name: 'Skill 3', description: 'React Native Prototype', priceRange: '$100' },
        { id: 4, name: 'Skill 4', description: 'Ready to use app', priceRange: '$400' },
      ],
      certificates: [
        {
          title: 'UI/UX Mastery',
          issuingOrganization: 'MySkill.id',
          dateEarned: '2023-08-19',
          photo: require('./certificate/uiux1.jpg'),
        },
        {
          title: 'UI/UX Mastery',
          issuingOrganization: 'SanberCode',
          dateEarned: '2023-02-24',
          photo: require('./certificate/uiux2.jpg'),
        },
        {
          title: 'React Native',
          issuingOrganization: 'SanberCode',
          dateEarned: '2023-01-21',
          photo: require('./certificate/reactnative.jpg'),
        },
        // Add more certificates as needed
      ],
    },
    { 
      id: 2,
      phoneNumber: '8293751748',
      pin: '9012735',
      role: 'worker',
      name: 'Jane Smith', 
      job: 'Web Development', 
      photo: require('./photo/photoProfile.png'), 
      productPhoto: require('./photo/project.png'),
      skills: [
        { id: 5, name: 'Skill 5', description: 'Web Design', priceRange: '$60' },
      ],
      certificates: [],
    },
    {
      id: 3, 
      phoneNumber: '910239742',
      pin: '728173',
      role: 'worker',
      name: 'Mike Johnson', 
      job: 'Mobile App Development', 
      photo: require('./photo/photoProfile.png'), 
      productPhoto: require('./photo/project.png') ,
      skills: [
        { id: 6, name: 'Skill 6', description: 'App Testing', priceRange: '$70' },
      ],
      certificates: [],
    },
    { 
      id: 4, 
      phoneNumber: '1212121212',
      pin: '121212',
      role: 'worker',
      name: 'Emily Brown', 
      job: 'Graphic Design', 
      photo: require('./photo/photoProfile.png'),
      productPhoto: require('./photo/project.png'),
      skills: [
        { id: 9, name: 'Skill 9', description: 'Logo Design', priceRange: '$90' },
      ],
      certificates: [],
    },
    { 
      id: 5, 
      phoneNumber: '9098762746',
      pin: '908762',
      role: 'worker',
      name: 'Alex Wilson', 
      job: 'Product Design', 
      photo: require('./photo/photoProfile.png'), 
      productPhoto: require('./photo/project.png'),
      skills: [
        { id: 10, name: 'Skill 10', description: 'Product Prototyping', priceRange: '$75' },
      ],
      certificates: [],
    },
    { 
      id: 6, 
      phoneNumber: '7878781234',
      pin: '987657',
      role: 'worker',
      name: 'Sara Davis', 
      job: 'Web Development', 
      photo: require('./photo/photoProfile.png'), 
      productPhoto: require('./photo/project.png') ,
      skills: [
        { id: 11, name: 'Skill 11', description: 'Frontend Development', priceRange: '$80' },
      ],
      certificates: [],
    },
    { 
      id: 7, 
      phoneNumber: '67128364751',
      pin: '090909',
      role: 'worker',
      name: 'Chris Thompson', 
      job: 'Mobile App Development', 
      photo: require('./photo/photoProfile.png'), 
      productPhoto: require('./photo/project.png') ,
      skills: [
        { id: 12, name: 'Skill 12', description: 'Backend Development', priceRange: '$100' },
      ],
      certificates: [],
    },
    { 
      id: 8, 
      phoneNumber: '8989898912',
      pin: '445454',
      role: 'worker',
      name: 'Rachel Miller', 
      job: 'Graphic Design',
      photo: require('./photo/photoProfile.png'),
      productPhoto: require('./photo/project.png') ,
      skills: [
        { id: 13, name: 'Skill 13', description: 'Print Design', priceRange: '$70' },
      ],
      certificates: [],
    },
    { 
      id: 9, 
      phoneNumber: '9018716273',
      pin: '989876',
      role: 'worker',
      name: 'Daniel Lee', 
      job: 'Product Design', 
      photo: require('./photo/photoProfile.png'), 
      productPhoto: require('./photo/project.png'),
      skills: [
        { id: 14, name: 'Skill 14', description: '3D Modeling', priceRange: '$120' },
      ],
      certificates: [],
    },
    { 
      id: 10, 
      phoneNumber: '9090909090',
      pin: '909090',
      role: 'worker',
      name: 'Sophie Clark', 
      job: 'Web Development', 
      photo: require('./photo/photoProfile.png'), 
      productPhoto: require('./photo/project.png') ,
      skills: [
        { id: 15, name: 'Skill 15', description: 'Responsive Design', priceRange: '$90' },
      ],
      certificates: [],
    },
    { 
      id: 11, 
      phoneNumber: '7827367284',
      pin: '817283',
      role: 'worker',
      name: 'Ryan White', 
      job: 'Mobile App Development', 
      photo: require('./photo/photoProfile.png'), 
      productPhoto: require('./photo/project.png') ,
      skills: [
        { id: 16, name: 'Skill 16', description: 'UI/UX Design', priceRange: '$90' },
      ],
      certificates: [],
    },
    { 
      id: 12, 
      phoneNumber: '718637246',
      pin: '871826',
      role: 'worker',
      name: 'Olivia Martinez', 
      job: 'Graphic Design', 
      photo: require('./photo/photoProfile.png'), 
      productPhoto: require('./photo/project.png'),
      skills: [
        { id: 17, name: 'Skill 17', description: 'Illustration', priceRange: '$80' },
      ],
      certificates: [],
    },
    { 
      id: 13, 
      phoneNumber: '8177826374',
      pin: '989898',
      role: 'worker',
      name: 'Andrew Taylor', 
      job: 'Product Design',
      photo: require('./photo/photoProfile.png'), 
      productPhoto: require('./photo/project.png') ,
      skills: [
        { id: 18, name: 'Skill 18', description: 'Packaging Design', priceRange: '$95' },
      ],
      certificates: [],
    },
    { 
      id: 14, 
      phoneNumber: '1231231234',
      pin: '234551',
      role: 'worker',
      name: 'Jessica Carter', 
      job: 'Web Development', 
      photo: require('./photo/photoProfile.png'), 
      productPhoto: require('./photo/project.png') ,
      skills: [
        { id: 19, name: 'Skill 19', description: 'JavaScript Development', priceRange: '$85' },
      ],
      certificates: [],
    },
    { 
      id: 15, 
      phoneNumber: '8787878712',
      pin: '901813',
      role: 'worker',
      name: 'Benjamin Harris', 
      job: 'Mobile App Development', 
      photo: require('./photo/photoProfile.png'), 
      productPhoto: require('./photo/project.png'),
      skills: [
        { id: 20, name: 'Skill 20', description: 'Mobile UI Design', priceRange: '$100' },
      ],
      certificates: [],
    },
  ];

  export const jobCategories = [
    'Product Design',
    'Web Development',
    'Mobile App Development',
    'Graphic Design',
  ];

export default workerData;